project_id = "fkvtnyvttgjiherassmn"

[functions.onboard-user]
verify_jwt = false

[functions.test-middleware]
verify_jwt = false

[functions.twilio-webhook]
verify_jwt = false

[functions.twilio-status]
verify_jwt = false

[functions.ai-twin-chat]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = false